version: '3'

services:
  nginx:
    container_name: laravel-tutorial_nginx
    build:
      context: ./nginx
    volumes:
      - ./web:/var/www
    ports:
      - "8000:80"
    links:
      - php-fpm
  
  php-fpm:
    container_name: laravel-tutorial_php-fpm
    build:
      context: ./web
    volumes:
      - ./web:/var/www/:cached
    links:
      - mysql
  
  mysql:
    container_name: laravel-tutorial_mysql
    image: mysql:latest
    platform: linux/amd64
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel-tutorial
    ports:
      - 3306:3306
